#industry
Industry.create(name: 'メーカー')
Industry.create(name: '商社')
Industry.create(name: '小売')
Industry.create(name: '金融')
Industry.create(name: 'サービス・インフラ')
Industry.create(name: 'ソフトウエア')
Industry.create(name: '広告・出版・マスコミ')
Industry.create(name: '官公庁・公社・団体')

#occupation
Occupation.create(name: '営業')
Occupation.create(name: '企画・管理')
Occupation.create(name: '事務・アシスタント')
Occupation.create(name: '販売・サービス職')
Occupation.create(name: 'コンサル')
Occupation.create(name: '金融系専門職')
Occupation.create(name: '公務員・教員・農林水産関連職')
Occupation.create(name: '技術職（SE・ITエンジニア）')
Occupation.create(name: '技術職（機械・電気）')
Occupation.create(name: '技術職（組み込みソフトウェア）')
Occupation.create(name: '技術職・専門職（建設・建築）')
Occupation.create(name: '技術職（化学・素材・化粧品）')
Occupation.create(name: '医療系専門職')
Occupation.create(name: 'クリエイター・クリエイティブ職')
